name: Beauty's Boho
favicon: null
layout_spectrum: 0.19531761459074914
typography_spectrum: 0.49261044431477785
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.622495076386258
  lightness: 0.4913865935523063
  saturation: 0.730728505179286
  rhythmicContrast: 0.16371516161598265
purpose: []
